### PR TITLE
Add Docusaurus

### PR DESCRIPTION
**Pull request by yangshun**

### CODE REVIEW

**Comment by Manvel** [comment]
Thanks @yangshun

@dertuxmalwieder, @balupton I will accept this, but I see some inconsistency between the requirements and what is being accepted and merged usually.

README sets "some level of requirement" for the fields below with the text of `At the very least, the following fields are required`, but I have noticed that MRs are and was accepted without communicating those fields:
`name`
`tags`
`github` or `gitlab` or `bitbucket` or `website`
`is`

I wonder if the README is outdated?

**Comment by dertuxmalwieder** [comment]
I didn't know whether to merge this. It's not quite clear if it fits the general category of SSGs from the description.

**Comment by yangshun** [comment]
Thanks for merging. Docusaurus is indeed a SSG just that it has features that are targeted at documentation. You're able to build normal sites with it as well. If mkdocs and readthedocs can be on the list, Docusaurus should be able to as well.

**Comment by Manvel** [comment]
@dertuxmalwieder arguably I can say same for other list items as well, but I have added `is` here -> https://github.com/bevry/staticsitegenerators-list/pull/333 to make it more clear if you in doubt, but I can't add `is` to other list items as I'm not familiar with most of the products.

**Pull request merged**
