### PR TITLE
Fix broken web site links

### PR DESCRIPTION
**Pull request by ddfreyne**

### CODE REVIEW

**Comment by ddfreyne** [comment]
Now fails with

> TypeError: Cannot read property 'message' of null

:|

**Comment by balupton** [comment]
yeah, due to rate limits being hit

I've added the needed env vars to the travis setup, but seems they won't apply on the PR

I've added you to the SSGs team, so you have write access to this repo, feel free to merge, as the merge should work - if it doesn't, then happy for you to work off master, and to keep up the great work uninhibited!

**Comment by balupton** [comment]
from the merge commit build:

```
Comparison Error:
AssertionError: there was automated data written into the manual listing, this has been removed, run the tests again
    at equal (/home/travis/build/bevry/staticsitegenerators-list/node_modules/assert-helpers/source/index.js:171:10)
    at EventEmitterGrouped.<anonymous> (/home/travis/build/bevry/staticsitegenerators-list/test.js:105:6)
    at ambi (/home/travis/build/bevry/staticsitegenerators-list/node_modules/ambi/source/index.js:91:18)
    at Domain.fireMethod (/home/travis/build/bevry/staticsitegenerators-list/node_modules/taskgroup/source/lib/task.js:519:5)
    at Domain.run (domain.js:221:14)
    at EventEmitterGrouped.fire (/home/travis/build/bevry/staticsitegenerators-list/node_modules/taskgroup/source/lib/task.js:537:15)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Comparison Diff:
```

not a useful comparison diff there, we should probably output specifically which fields for which entries it is complaining about, rather than doing a diff

that said, all it needs is a local run, and commit of the changes, and a push up

**Comment by balupton** [comment]
do you want to do the local build, commit, and push?

**Comment by ddfreyne** [comment]
I’ll take care of it!

**Comment by ddfreyne** [comment]
Back to green!

**Comment by balupton** [comment]
@ddfreyne and deployed it seems! great work!

**Pull request merged**
