### PR TITLE
Add website link for Lektor

### PR DESCRIPTION
**Pull request by chaos95**
Add a website link for Lektor (python SSG), obtained from the project's Github repo description.

### CODE REVIEW

**Comment by balupton** [comment]
Hrmm. If the github repo has it, then it will end up getting trimmed off by the tests. I'll update the tests to fail instead of warn now that the trims have taken place.

**Comment by balupton** [comment]
Okay, this seems to be my fault. The tests did not correctly trim the data. All fixed. Thanks for the submission. In the future, adding information that github's API provides will get trimmed out and cause the tests to fail - however running the tests locally again will pass as the `list.json` will have the automated data trimmed.

**Comment by balupton** [comment]
In case what I said is not clear, what we do is take the source `list.json` file from this repo, and then enhance it with data from APIs, so the rendered listing - https://staticsitegenerators.net/list.json - will include the github URL if it is set.

**Comment by chaos95** [comment]
Thanks for reviewing this! Happy to have uncovered a fixable issue :)

**Pull request closed without merging**
