### PR TITLE
update list.yaml

### PR DESCRIPTION
**Pull request by packetrhino**
Add REXX based PPWizard tool.

### CODE REVIEW

**Comment by balupton** [comment]
this seems more like a templating language that a ssg, is there anything in there that helps you generate say a 1000 document website? or do you have to render each document individually, or write a script to render them all?

**Comment by packetrhino** [comment]
Yes, I have used it in the past to create a 30 or 40 page document with
links to each other.

There are a lot of REXX programmers out there (usually from the IBM
minicomputer and mainframe world, though the REXX interpreter runs on
Windows and Linux too) so I thought it should be added.  It's a "fringe"
language in Unix scripting , admittedly.

The Beginner's Guide covers the main points, linked from the main page.
Conventions are .it for a document and .ih for includes in the style of C
programming language includes.

You can generate all the docs (assuming in 1 directory) with e.g.

ppwizard *.it

With the source files named e.g. page1.it, page2.it .

You can control the output directory and whether it uses .htm , .html etc.

It can also do dependency checking and only regenerate those pages
that have changed.

**Comment by balupton** [comment]
Sounds good to me!

**Comment by balupton** [comment]
Looking at your profile, seems you created a GitHub profile just for this? Very cool! 💯

**Pull request merged**
