### PR TITLE
Added blogcpp

### PR DESCRIPTION
**Pull request by dertuxmalwieder**

### CODE REVIEW

**Comment by wifiextender** [comment]
Add the following:

```javascript
  website: "https://bitbucket.org/tux_/blogcpp"
```

**Comment by dertuxmalwieder** [comment]
^ Updated.

**Comment by wifiextender** [comment]
@dertuxmalwieder You can also add interactive search form, [here's] the code.

[here's]:  https://wifiextender.github.io/#!post=search_form

**Comment by dertuxmalwieder** [comment]
I have plans for a search, probably revolving around generating an index file as the last step and using tipue_search. But my plans may change. I bookmarked your link, thanks. :)

**Comment by davisonio** [comment]
Added, thanks!

**Comment by dertuxmalwieder** [comment]
Thank you!

**Pull request merged**
