### PR TITLE
Add Almace Scaffolding

### PR DESCRIPTION
**Pull request by TheLastZombie**

### CODE REVIEW

**Comment by dertuxmalwieder** [comment]
Hmm. Does this count as a SSG as it’s only an addition to one?

**Comment by TheLastZombie** [comment]
Hmm, good point. I saw it listed on [staticgen.com](https://www.staticgen.com/), and if I remember correctly there was an issue to support other generators as well, but it was closed some time after.

I always saw it as a separate generator (additional Grunt tasks, own theme ecosystem etc.), but ultimately it's up to you.

**Comment by dertuxmalwieder** [comment]
StaticGen has weird criteria anyway. They only support GitHub. Pfff...

**Comment by davisonio** [comment]
yeah seems this is just a framework not a SSG

**Pull request closed without merging**
